yeelali14 PR
yeelali14/EuropeanPaintings pull request #15
Opened 2022-02-24 13:07 UTC by yeelali14

2022-02-24 14:13 UTC, vim-zz requested changes
LGTM

2022-02-24 15:48 UTC, ShakedZrihen commented on README.md
> +1) Install Angular CLI: `npm install -g @angular/cli`
Please use React instead

2022-02-24 15:49 UTC, ShakedZrihen requested changes
angular is so 2016

2022-02-27 13:57 UTC, slowHand14 commented on README.md
> +#PR
👍

2022-02-27 17:33 UTC, slowHand14 commented on README.md
> +## Development server
👍

2022-03-29 11:25 UTC, closed without merging