Update README.md
yeelali14/EuropeanPaintings pull request #9
Opened 2022-02-20 17:37 UTC by ShakedZrihen

2022-02-20 18:19 UTC, slowHand14 reviewed
nb,

2022-02-20 18:19 UTC, slowHand14 reviewed
m,mnm

2022-02-20 18:22 UTC, yeelali14 reviewed
test

2022-02-23 11:44 UTC, nogaZohar commented on README.md
> +LOLIPOP
please use lower case here

2022-02-23 11:45 UTC, nogaZohar requested changes
see comment

2022-02-23 11:51 UTC, yeelali14 commented on README.md
> +LOLIPOP
test

2022-02-23 11:53 UTC, yeelali14 commented on README.md
> +LOLIPOP
works?

2022-02-23 12:58 UTC, closed without merging